#ifndef SENSUS_MEASUREMENT_CONFIG_H
#define SENSUS_MEASUREMENT_CONFIG_H

/* Archived firmware configuration for L-DOPA I-T, +0.2 V, 180 s. */
#define GUI_WP_FSR MAX30131_FSR_2000NA
#define GUI_WP_OFFSET_SEL MAX30131_OFFSET_10PCT_FSR
#define GUI_WP_START_E_MV 200
#define GUI_WP_E_MV 200
#define GUI_PRESTEP_DURATION_MS 0U
#define GUI_MEASUREMENT_DURATION_MS 180000U

#define GUI_SENS_PERIOD_CODE 0x0U
#define GUI_SENS_PERIOD_MS 124U

#endif
