#ifndef SENSUS_MEASUREMENT_CONFIG_H
#define SENSUS_MEASUREMENT_CONFIG_H

/* Safe source-tree defaults; the GUI writes measurement_config.h at runtime. */
#define GUI_WP_FSR MAX30131_FSR_2000NA
#define GUI_WP_OFFSET_SEL MAX30131_OFFSET_10PCT_FSR
#define GUI_WP_START_E_MV 200
#define GUI_WP_E_MV 200
#define GUI_PRESTEP_DURATION_MS 0U
#define GUI_MEASUREMENT_DURATION_MS 180000U
#define GUI_IT_ADAPTIVE_STOP 0
#define GUI_IT_USE_EIS 0
#define GUI_IT_EIS_FSR MAX30131_EIS_FSR_40UA
#define GUI_IT_SAMPLE_INTERVAL_MS 100U

#define GUI_MEASUREMENT_MODE_CV 0
#define GUI_WP_V_WE_MV 1200
#define GUI_CV_V_WE_MV 800
#define GUI_CV_LOW_E_MV -600
#define GUI_CV_HIGH_E_MV 600
#define GUI_CV_SCAN_RATE_MV_S 50U
#define GUI_CV_CYCLES 30U
#define GUI_CV_STEP_MV 1U
#define GUI_CV_STEP_INTERVAL_MS 20U
#define GUI_CV_QUIET_DURATION_MS 2000U
#define GUI_CV_EIS_FSR MAX30131_EIS_FSR_40UA

#define GUI_SENS_PERIOD_CODE 0x0U
#define GUI_SENS_PERIOD_MS 124U

#endif
